global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'saturn-turn-server'
    static_configs:
      - targets: ['saturn:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    basic_auth:
      username: 'admin'
      password: 'secret'  # Must match METRICS_USERNAME/PASSWORD
